version: '3.8'

services:
  shop:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    ports:
      - 8000:8000
    command: bash -c "python manage.py runserver   0.0.0.0:8000"
    depends_on:
      - db

  db:
    image: postgres:12
    environment:
    - "POSTGRES_HOST_AUTH_METHOD=trust"
    - "POSTGRES_DB=${DB_NAME}"
    - "POSTGRES_USER=${DB_USER}"
    - "PGUSER=${DB_USER}"
    - "POSTGRES_PASSWORD=${DB_PASSWORD}"
    ports:
      - 5432:5432
    volumes:
      - shop:/var/lib/postgresql/data

volumes:
  shop:
    name: shop
    external: true
