services:
  shop:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    env_file:
      - ./.env
    expose:
      - 8000
    command: bash -c "gunicorn --bind 0.0.0.0:8000 OnlineShop.wsgi:application"
    volumes:
      - static_volume:/app/static/
      - shop:/data
    depends_on:
      - db

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      PGUSER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - 5432:5432
    volumes:
      - shop:/var/lib/postgresql/data

  nginx:
    build: ./nginx
    restart: always
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - shop

volumes:
  static_volume:
  media_volume:
  shop:
    name: shop
    external: true
