services:
  shop:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - shop_net

  db:
    image: postgres:12
    environment:
    - "POSTGRES_HOST_AUTH_METHOD=trust"
    - "POSTGRES_DB=${DB_NAME}"
    - "PGUSER=${DB_USER}"
    - "PGPASSWORD=${DB_PASSWORD}"
    - "PGPORT=${DB_PORT}"
    volumes:
      - shop:/var/lib/postgresql/data
    networks:
      - shop_net

volumes:
  shop:
    name: shop

networks:
  shop_net:
    driver: bridge
