version: '3.8'

services:
  shop:
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    container_name: online-shop-container
    environment:
      - DB_DIR=/data
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    ports:
      - 8000:9000
    image: ${IMAGE_NAME}
    build:
      context: .
      dockerfile: ./Dockerfile
    command: bash -c "python /app/manage.py migrate && python /app/manage.py runserver 0.0.0.0:8000"
    volumes:
      - shop:/data
    depends_on:
      - db

  db:
    restart: unless-stopped
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5433:5433
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    restart: unless-stopped
    image: nginx:latest
    container_name: nginx-container
    ports:
      - 80:80
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - shop

volumes:
  static_volume:
  media_volume:
  shop:
    name: shop
    external: true
  pgdata:
    name: pgdata
