version: '3.8'

services:
  shop:
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    container_name: online-shop-container
    environment:
      - DB_DIR=/data
    ports:
      - 8000:9000
      - 5432:5432
    image: ${IMAGE_NAME}
    build:
      context: .
      dockerfile: ../Dockerfile
    command: bash -c "python /app/manage.py migrate && python /app/manage.py runserver 0.0.0.0:8000"
    volumes:
      - shop:/data

volumes:
  shop:
    name: shop
    external: true
